# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_musicrecommendation_suggestion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together=set([('name', 'created_by')]),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set([('artist', 'song_name')]),
        ),
    ]
